Repository sopra-fs24-group-26/client, pull requests merged in 2024-03, with the labels that each got.

#32 Initial Logic and System Architecture: Create frontend phaser structure
  src/App.tsx
  src/core/App.tsx
  src/core/EventBus.ts
  src/core/PhaserGame.tsx
  src/core/main.ts
  src/index.tsx
  src/scenes/titlescreen.ts
  src/tests/App.test.tsx
  src/utilities/api.ts
Labels: enhancement

#34 33: Add README.md pattern, workflow and formatting
  README.md
Labels: documentation

#36 Initial logic and system architecture: Change main to master
  .github/workflows/main.yml
Labels: bug

#35 Initial Logic and System Architecture: Create phaser scene structure with router
  src/core/EventBus.ts
  src/core/PhaserGame.tsx
  src/core/main.ts
  src/core/masterTick.ts
  src/managers/PlayerManager.ts
  src/managers/SessionManager.ts
  src/scenes/titlescreen.ts
  src/utilities/AbstractEventEmitter.ts
  src/utilities/AsyncEventEmitter.ts
  src/utilities/EventEmitter.ts
  src/utilities/logger.ts
  src/utilities/utils.ts
Labels: enhancement
