Repository sopra-fs24-group-26/client, pull requests merged in 2024-05, with the labels that each got.

#102 U03: A new player is only able to join in the lobby
  src/managers/SessionManager.ts
Labels: enhancement

#101 U10: The player can discard an item of his choice from his hand
  public/assets/buttons/trashcan.png
  src/definitions/dto.ts
  src/entities/Tile.ts
  src/managers/TileManager.ts
  src/scenes/gameuiscreen.ts
Labels: enhancement

#100 U04: Refactor adjacency manager and detect when gold vein is connected to start
  src/definitions/adjacency.ts
  src/definitions/placeTile.ts
  src/managers/AdjacencyManager.ts
  src/managers/TileManager.ts
  src/scenes/gamescreen.ts
  src/scenes/gameuiscreen.ts
  src/utilities/AdjacencyMap.ts
Labels: enhancement

#105 U11: Implement game end logic
  public/assets/tiles/tile10.png
  public/assets/tiles/tile12.png
  public/assets/tiles/tile9.png
  src/configs/tiles.json
  src/core/main.ts
  src/entities/Tile.ts
  src/managers/AdjacencyManager.ts
  src/managers/SessionManager.ts
  src/managers/TileManager.ts
  src/scenes/endscreen.ts
  src/scenes/gamescreen.ts
  src/scenes/gameuiscreen.ts
  src/utilities/AdjacencyMap.ts
Labels: enhancement

#107 U10: Refactor discard and connectiontostart logic
  src/configs/nameGeneration.json
  src/managers/AdjacencyManager.ts
  src/managers/PlayerManager.ts
  src/managers/SessionManager.ts
  src/managers/TileManager.ts
  src/scenes/endscreen.ts
  src/scenes/gamescreen.ts
  src/scenes/gameuiscreen.ts
  src/utilities/AdjacencyMap.ts
Labels: bug

#125 U19: Add ore-shower to endscreen
  public/assets/particles/coalNugget.png
  public/assets/particles/goldNugget.png
  src/core/main.ts
  src/scenes/endscreen.ts
  src/scenes/gamescreen.ts
Labels: enhancement

#126 U14/U18: Every Player has a visual representation of its role, sees other players and whose turn it is
  public/assets/profiles/profile0.png
  public/assets/profiles/profile1.png
  public/assets/profiles/profile2.png
  public/assets/profiles/profile3.png
  public/assets/profiles/profile4.png
  public/assets/profiles/ring.png
  src/entities/Player.ts
  src/managers/SessionManager.ts
  src/scenes/endscreen.ts
  src/scenes/gamescreen.ts
  src/scenes/gameuiscreen.ts
  src/scenes/lobbyscreen.ts
Labels: enhancement

#127 U17: Build avatar into game using API
  package-lock.json
  package.json
  src/entities/Player.ts
  src/scenes/endscreen.ts
  src/scenes/gameuiscreen.ts
  src/scenes/lobbyscreen.ts
Labels: enhancement

#151 Clean up sprint 2: Improve bad tile placement prompt
  src/scenes/gameuiscreen.ts
Labels: enhancement

#147 Clean up sprint 2: Display join error
  src/managers/SessionManager.ts
Labels: enhancement

#154 Update ReadMe Client Description: Update Licensing
  LICENSE
Labels: documentation

#153 Clean up sprint 2: Add message on share
  src/scenes/lobbyscreen.ts
Labels: enhancement

#155 Clean up sprint 2: Fix garbage code
  src/managers/SessionManager.ts
  src/managers/TileManager.ts
  src/scenes/endscreen.ts
  src/scenes/gamescreen.ts
  src/scenes/gameuiscreen.ts
  src/scenes/lobbyscreen.ts
  src/utilities/AdjacencyMap.ts
Labels: bug, unholy

#157 Clean up Github Repository: Update ReadMe Client Decsription
  README.md
Labels: documentation

#158 U16: Create missing unknown vein, eye art
  public/assets/tiles/tile10.png
  public/assets/tiles/tile14.png
  public/assets/tiles/tile9.png
Labels: enhancement

#156 U21: Add gamerules scene and controls button in gamuiscreen
  public/assets/controlsexplained.png
  src/configs/gameRules.json
  src/core/main.ts
  src/scenes/gamerulesscreen.ts
  src/scenes/gameuiscreen.ts
  src/scenes/lobbyscreen.ts
Labels: enhancement

#161 Clean up sprint 2: Finish minor fixes
  public/Monocraft.woff2
  public/assets/buttons/quit.png
  public/assets/profiles/profile0.png
  public/assets/profiles/profile1.png
  public/assets/profiles/profile2.png
  public/assets/profiles/profile3.png
  public/assets/profiles/profile4.png
  public/index.html
  src/configs/gameRules.json
  src/configs/preplacedTiles.json
  src/core/main.ts
  src/managers/SessionManager.ts
  src/scenes/endscreen.ts
  src/scenes/gamerulesscreen.ts
  src/scenes/gamescreen.ts
  src/scenes/gameuiscreen.ts
  src/scenes/lobbyscreen.ts
  src/scenes/titlescreen.ts
Labels: bug, enhancement, unholy

#163 Clean up sprint 2: Change font type to ttf
  public/Monocraft.ttf
  public/Monocraft.woff2
  public/index.html
Labels: bug

#166 Clean up sprint 2: Change font size
  src/scenes/lobbyscreen.ts
Labels: enhancement

#167 Clean up sprint 2: Better formatting lobby
  src/scenes/lobbyscreen.ts
Labels: enhancement

#168 Clean up sprint 2: Make text prettier and more adaptable to screen size
  public/assets/fonts/YosterIslandRegBitmap.fnt
  public/assets/fonts/YosterIslandRegBitmap.png
  public/assets/fonts/license.txt
  public/assets/fonts/yoster.ttf
  public/index.html
  src/core/main.ts
  src/managers/TileManager.ts
  src/scenes/endscreen.ts
  src/scenes/gamerulesscreen.ts
  src/scenes/gameuiscreen.ts
  src/scenes/lobbyscreen.ts
  src/scenes/titlescreen.ts
  src/utilities/api.ts
Labels: enhancement
